[package]
name = "grpcio-proto"
version = "0.4.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["grpc", "proto"]
repository = "https://github.com/pingcap/grpc-rs"
homepage = "https://github.com/pingcap/grpc-rs"
documentation = "https://docs.rs/grpcio-sys"
description = "Public proto files for grpcio."
categories = ["network-programming"]
build = "build.rs"

[dependencies]
protobuf = "~2.2"
futures = "0.1"
grpcio = { path = "..", version = "0.4.0" }

[build-dependencies]
protobuf = "~2.2"
protobuf-codegen = "~2.2"
grpcio-compiler = { path = "../compiler", version = "0.4.0" }
